spring:
  application:
    name: report-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/
    serviceUrl:
      defaultZone: http://localhost:8303/eureka/
  instance:
    hostname: localhost

server:
  port: 8302
