spring:
  application:
    name: gateway-service

server:
  port: 8304

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    #    service-url:
    #      default-zone: http://localhost:8761/eureka/
    serviceUrl:
      defaultZone: http://localhost:8303/eureka/
  instance:
    hostname: localhost

zuul:
  prefix: /api
  ignored-services: '*'
  routes:
    db:
      path: /db-gateway/**
      service-id: db-service
#      url: http://localhost:8300
    report:
      path: /report-gateway/**
      service-id: report-service
#      url: http://localhost:8302

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
#  eureka:
#    enabled: true

